---
- name: Create Directories
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
   - file:
       path: /opt/analytics
       state: directory
       owner: cloudbreak
       group: cloudbreak
       mode: 0775

- name: Syncing
  hosts: compute:data:!gateway
  tasks:
    - synchronize:
        src: /opt/analytics/anaconda
        dest: /opt/analytics/
      delegate_to: gateway